import { useEffect, useMemo, useState, type ReactNode } from "react";
import dagre from "@dagrejs/dagre";
import { Background, Controls, Handle, Position, ReactFlow, ReactFlowProvider, useReactFlow, type Node, type NodeProps, type Edge } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { getAutomationBlueprint, getRedesignProposal } from "../api/workflows";
import { ScoreTooltip } from "./ScoreTooltip";
import { riskExplanation, riskLabel, riskScore, textBullets } from "../utils/workflow";
import type { AutomationBlueprint, RedesignProposal, StaticWorkflowDiagram, StepScore, Verdict, Workflow } from "../types/workflow";

type StepNodeData = { step: Workflow["steps"][number]; score?: StepScore; stepNumber: number };
type StepNode = Node<StepNodeData, "workflowStep">;
const NODE_WIDTH = 300;
const NODE_HEIGHT = 170;

export function WorkflowDiagram(props: { workflow: Workflow; onWorkflowChange: (workflow: Workflow) => void; selectedStepId?: string; onStepSelect?: (stepId: string) => void } | { diagram: StaticWorkflowDiagram }) {
  if ("diagram" in props) return <GeneratedDiagram diagram={props.diagram} />;
  return <InteractiveWorkflowDiagram workflow={props.workflow} onWorkflowChange={props.onWorkflowChange} selectedStepId={props.selectedStepId} onStepSelect={props.onStepSelect} />;
}

function InteractiveWorkflowDiagram({ workflow, onWorkflowChange, selectedStepId: selectedStepIdProp, onStepSelect }: { workflow: Workflow; onWorkflowChange: (workflow: Workflow) => void; selectedStepId?: string; onStepSelect?: (stepId: string) => void }) {
  const [internalSelectedStepId, setInternalSelectedStepId] = useState<string | null>(workflow.steps[0]?.step_id ?? null);
  const selectedStepId = selectedStepIdProp ?? internalSelectedStepId;
  const [notes, setNotes] = useState("");
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [error, setError] = useState("");
  const selectedStep = workflow.steps.find((step) => step.step_id === selectedStepId);
  const selectedScore = workflow.scores.find((score) => score.step_id === selectedStepId);
  const { nodes, edges } = useMemo(() => layoutWorkflow(workflow), [workflow]);
  const selectedOutput = selectedScore?.verdict === "automate" ? workflow.automation_blueprints?.find((item) => item.step_id === selectedScore.step_id) : workflow.redesign_proposals?.find((item) => item.step_id === selectedScore?.step_id);

  async function regenerate() {
    if (!selectedStep || !selectedScore || !notes.trim()) return;
    setIsRegenerating(true); setError("");
    try {
      if (selectedScore.verdict === "automate") {
        const blueprint = await getAutomationBlueprint(workflow.workflow_id, selectedStep.step_id, notes);
        onWorkflowChange({ ...workflow, automation_blueprints: [...(workflow.automation_blueprints ?? []).filter((item) => item.step_id !== selectedStep.step_id), blueprint] });
      } else if (selectedScore.verdict === "redesign") {
        const proposal = await getRedesignProposal(workflow.workflow_id, selectedStep.step_id, notes);
        onWorkflowChange({ ...workflow, redesign_proposals: [...(workflow.redesign_proposals ?? []).filter((item) => item.step_id !== selectedStep.step_id), proposal] });
      }
      setNotes("");
    } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Regeneration failed."); }
    finally { setIsRegenerating(false); }
  }

  function selectStep(stepId: string) { setInternalSelectedStepId(stepId); onStepSelect?.(stepId); setError(""); }
  return <div className="space-y-5"><StepCanvas nodes={nodes} edges={edges} activeStepId={selectedStepId} onSelect={selectStep} /><StepPanel step={selectedStep} score={selectedScore} output={selectedOutput} notes={notes} error={error} isRegenerating={isRegenerating} onNotesChange={setNotes} onRegenerate={regenerate} /></div>;
}

function StepCanvas(props: { nodes: StepNode[]; edges: Edge[]; activeStepId: string | null; onSelect: (stepId: string) => void }) { return <ReactFlowProvider><StepCanvasInner {...props} /></ReactFlowProvider>; }

function StepCanvasInner({ nodes, edges, activeStepId, onSelect }: { nodes: StepNode[]; edges: Edge[]; activeStepId: string | null; onSelect: (stepId: string) => void }) {
  const { setCenter } = useReactFlow();
  const activeIndex = Math.max(0, nodes.findIndex((node) => node.id === activeStepId));
  const centerNode = (node: StepNode) => { onSelect(node.id); setCenter(node.position.x + NODE_WIDTH / 2, node.position.y + NODE_HEIGHT / 2, { zoom: 1.05, duration: 450 }); };
  useEffect(() => { const node = nodes.find((item) => item.id === activeStepId); if (node) setCenter(node.position.x + NODE_WIDTH / 2, node.position.y + NODE_HEIGHT / 2, { zoom: 0.9, duration: 0 }); }, [activeStepId, nodes, setCenter]);
  const move = (offset: number) => { const node = nodes[Math.min(nodes.length - 1, Math.max(0, activeIndex + offset))]; if (node) centerNode(node); };
  return <div><div className="h-[620px] w-full overflow-hidden rounded-[24px] border border-blue-100 bg-cloud shadow-card sm:h-[680px]"><ReactFlow nodes={nodes} edges={edges} nodeTypes={{ workflowStep: WorkflowStepNode }} fitView fitViewOptions={{ padding: 0.2, minZoom: 0.45, maxZoom: 1 }} minZoom={0.35} maxZoom={1.5} onNodeClick={(_, node) => { const selected = nodes.find((item) => item.id === node.id); if (selected) centerNode(selected); }} nodesConnectable={false} nodesDraggable={false} elementsSelectable><Background color="var(--color-brand-soft)" gap={24} /><Controls showInteractive={false} /></ReactFlow></div><div className="mt-3 flex flex-wrap items-center justify-center gap-2 rounded-[20px] border border-blue-100 bg-white p-3 shadow-card"><button type="button" onClick={() => move(-1)} disabled={activeIndex === 0} aria-label="Previous step" className="rounded-full border border-blue-100 px-3 py-2 text-sm font-semibold text-slate-600 transition hover:border-brand hover:text-brand disabled:cursor-not-allowed disabled:opacity-40">← Previous</button>{nodes.map((node, index) => <button type="button" key={node.id} onClick={() => centerNode(node)} aria-label={`Center step ${index + 1}`} aria-current={node.id === activeStepId ? "step" : undefined} className={`grid h-9 w-9 place-items-center rounded-full text-sm font-bold transition ${node.id === activeStepId ? "bg-brand text-white shadow" : "border border-blue-100 bg-white text-slate-500 hover:border-brand hover:text-brand"}`}>{index + 1}</button>)}<button type="button" onClick={() => move(1)} disabled={activeIndex === nodes.length - 1} aria-label="Next step" className="rounded-full border border-blue-100 px-3 py-2 text-sm font-semibold text-slate-600 transition hover:border-brand hover:text-brand disabled:cursor-not-allowed disabled:opacity-40">Next →</button></div></div>;
}

function GeneratedDiagram({ diagram }: { diagram: StaticWorkflowDiagram }) { return <ReactFlowProvider><GeneratedDiagramInner diagram={diagram} /></ReactFlowProvider>; }
function GeneratedDiagramInner({ diagram }: { diagram: StaticWorkflowDiagram }) { const { setCenter } = useReactFlow(); const nodes = layoutGeneratedNodes(diagram); const edges = diagram.edges.map((edge) => ({ id: `${edge.source}-${edge.target}`, source: edge.source, target: edge.target, animated: false, style: { stroke: "var(--color-brand)", strokeWidth: 2 } })); return <div className="h-[360px] overflow-hidden rounded-[24px] border border-blue-100 bg-cloud shadow-card"><ReactFlow nodes={nodes} edges={edges} fitView nodesConnectable={false} nodesDraggable={false} onNodeClick={(_, node) => { const target = nodes.find((item) => item.id === node.id); if (target) setCenter(target.position.x + 135, target.position.y + 50, { zoom: 1.05, duration: 450 }); }}><Background color="var(--color-brand-soft)" gap={24} /><Controls showInteractive={false} /></ReactFlow></div>; }

function layoutWorkflow(workflow: Workflow): { nodes: StepNode[]; edges: Edge[] } { const graph = new dagre.graphlib.Graph().setDefaultEdgeLabel(() => ({})); graph.setGraph({ rankdir: "LR", nodesep: 70, ranksep: 110, marginx: 50, marginy: 40 }); workflow.steps.forEach((step) => graph.setNode(step.step_id, { width: NODE_WIDTH, height: NODE_HEIGHT })); workflow.steps.slice(1).forEach((step, index) => graph.setEdge(workflow.steps[index].step_id, step.step_id)); dagre.layout(graph); const nodes = workflow.steps.map((step, index) => { const position = graph.node(step.step_id); return { id: step.step_id, type: "workflowStep" as const, position: { x: position.x - NODE_WIDTH / 2, y: position.y - NODE_HEIGHT / 2 }, data: { step, score: workflow.scores.find((score) => score.step_id === step.step_id), stepNumber: index + 1 }, draggable: false, selectable: true }; }); const edges = workflow.steps.slice(1).map((step, index) => ({ id: `${workflow.steps[index].step_id}-${step.step_id}`, source: workflow.steps[index].step_id, target: step.step_id, type: "smoothstep", animated: false, style: { stroke: "var(--color-brand)", strokeWidth: 2 } })); return { nodes, edges }; }

function WorkflowStepNode({ data }: NodeProps<StepNode>) { const { step, score } = data; const bullets = textBullets(step.description); return <div className="relative min-h-[170px] w-[300px] rounded-[22px] border border-blue-100 bg-white p-4 shadow-card"><Handle type="target" position={Position.Left} className="!border-brand !bg-blue-100" /><span className="absolute -left-3 -top-3 grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-brand font-display text-sm font-bold text-white shadow">{data.stepNumber}</span><div className="mb-3 flex items-start justify-between gap-2 pl-3"><p className="font-display text-sm font-semibold leading-5 text-ink">{step.name}</p>{score && <VerdictBadge verdict={score.verdict} />}</div><ul className="space-y-1 text-xs leading-4 text-slate-500">{bullets.slice(0, 3).map((item, index) => <li key={`${step.step_id}-${index}`} className="flex gap-2"><span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-brand" />{String(item)}</li>)}{bullets.length > 3 && <li className="pl-3 font-semibold text-brand">... more in details</li>}</ul><Handle type="source" position={Position.Right} className="!border-brand !bg-blue-100" /></div>; }

function layoutGeneratedNodes(diagram: StaticWorkflowDiagram) { const graph = new dagre.graphlib.Graph().setDefaultEdgeLabel(() => ({})); graph.setGraph({ rankdir: "LR", nodesep: 50, ranksep: 130, marginx: 40, marginy: 30 }); diagram.nodes.forEach((node) => graph.setNode(node.id, { width: 270, height: 100 })); diagram.edges.forEach((edge) => graph.setEdge(edge.source, edge.target)); dagre.layout(graph); return diagram.nodes.map((node) => { const position = graph.node(node.id); return { id: node.id, position: { x: position.x - 135, y: position.y - 50 }, data: { label: node.label }, style: { width: 270, borderRadius: 22, border: "1px solid var(--color-brand-soft)", background: node.node_type === "human_checkpoint" ? "#eef2ff" : "white", color: "var(--color-ink)", fontWeight: 600, padding: 14, boxShadow: "var(--shadow-card)" } }; }); }

function StepPanel({ step, score, output, notes, error, isRegenerating, onNotesChange, onRegenerate }: { step?: Workflow["steps"][number]; score?: StepScore; output?: AutomationBlueprint | RedesignProposal; notes: string; error: string; isRegenerating: boolean; onNotesChange: (value: string) => void; onRegenerate: () => void }) { if (!step || !score) return <aside className="rounded-2xl border border-dashed border-slate-300 bg-white p-6 text-sm text-slate-500">Select a step to inspect its details.</aside>; const risk = riskScore(score); return <aside className="overflow-y-auto rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-teal-700">Selected step</p><h2 className="mt-2 font-display text-xl font-semibold text-[#102a2c]">{step.name}</h2></div><VerdictBadge verdict={score.verdict} /></div><div className="mt-5 grid grid-cols-2 gap-2">{Object.entries(score.scores).map(([key, value]) => <ScoreTooltip key={key} dimension={key} explanation={score.reasoning}><Metric label={key.replaceAll("_", " ")} value={`${value}/5`} /></ScoreTooltip>)}<Metric label="risk if unaddressed" value={`${risk}/5 · ${riskLabel(risk)}`} /></div><p className="mt-3 text-xs leading-5 text-slate-600">{riskExplanation(score)}</p><PanelSection title="Description"><BulletList text={step.description} /></PanelSection><PanelSection title="Reasoning"><BulletList text={score.reasoning} /></PanelSection>{output && <PanelSection title={score.verdict === "automate" ? "Automation blueprint" : "Redesign proposal"}><OutputSummary output={output} verdict={score.verdict} /></PanelSection>}{score.verdict !== "leave_as_is" && <div className="mt-6 border-t border-slate-200 pt-5"><p className="font-display font-semibold text-[#102a2c]">Regenerate with notes</p><p className="mt-1 text-xs leading-5 text-slate-500">The instruction is appended to the existing generator prompt and replaces this step's saved output.</p><textarea value={notes} onChange={(event) => onNotesChange(event.target.value)} rows={4} placeholder="e.g. keep a human review step" className="mt-3 w-full resize-none rounded-xl border border-slate-200 px-3 py-2 text-sm leading-5 outline-none focus:ring-2 focus:ring-teal-600" /><button type="button" disabled={isRegenerating || !notes.trim()} onClick={onRegenerate} className="mt-3 w-full rounded-xl bg-[#102a2c] px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{isRegenerating ? "Regenerating..." : "Regenerate with notes"}</button>{error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-xs leading-5 text-red-700">{error}</p>}</div>}</aside>; }

function PanelSection({ title, children }: { title: string; children: ReactNode }) { return <section className="mt-6 border-t border-slate-200 pt-5"><p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-400">{title}</p>{children}</section>; }
function BulletList({ text }: { text: string }) { return <ul className="space-y-2 text-sm leading-6 text-slate-600">{textBullets(text).map((item, index) => <li key={`${item}-${index}`} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-teal-600" />{String(item)}</li>)}</ul>; }
function OutputSummary({ output, verdict }: { output: any; verdict: Verdict }) { return <div className="grid gap-3 sm:grid-cols-2"><ComparisonColumn label="Before" title={output.current_step.name} text={output.current_step.description} /><ComparisonColumn label="After" title={verdict === "automate" ? mechanismLabel(output.mechanism_type) : "Proposed redesign"} text={verdict === "automate" ? [output.trigger_condition, output.rationale].join(". ") : [output.proposed_design, ...output.agent_responsibilities, ...output.human_controls].join(". ")} /></div>; }
function mechanismLabel(value: string): string { return ({ rpa: "Robotic Process Automation (RPA)", rules_engine: "Rules engine", scheduled_job: "Scheduled job", existing_stp_extension: "Existing straight-through processing extension" } as Record<string, string>)[value] ?? value.replaceAll("_", " "); }
function ComparisonColumn({ label, title, text }: { label: string; title: string; text: string }) { return <div className={`rounded-xl p-3 ${label === "Before" ? "bg-slate-50" : "bg-[#e4eee9]"}`}><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-teal-700">{label}</p><p className="mt-1 font-display text-sm font-semibold text-[#102a2c]">{title}</p><BulletList text={text} /></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] uppercase leading-4 tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-[#102a2c]">{String(value)}</p></div>; }
function VerdictBadge({ verdict }: { verdict: Verdict }) { const styles = { automate: "bg-emerald-100 text-emerald-800", redesign: "bg-amber-100 text-amber-800", leave_as_is: "bg-slate-100 text-slate-700" }; return <span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-wide ${styles[verdict]}`}>{verdict.replaceAll("_", " ")}</span>; }
