import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getAutomationBlueprint, getWorkflow } from "../api/workflows";
import { WorkflowDiagram } from "../components/WorkflowDiagram";
import type { AutomationBlueprint } from "../types/workflow";
import { textBullets } from "../utils/workflow";
import { ScreenChat } from "../components/ScreenChat";
import { storedScreenContext } from "../utils/workflow";

export function AutomationBlueprintPage() {
  const { workflowId, stepId } = useParams();
  const [blueprint, setBlueprint] = useState<AutomationBlueprint | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { if (!workflowId || !stepId) return; getWorkflow(workflowId).then((workflow) => { const saved = workflow.automation_blueprints?.find((item) => item.step_id === stepId); if (saved) return setBlueprint(saved); return getAutomationBlueprint(workflowId, stepId).then(setBlueprint); }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Blueprint load failed.")); }, [workflowId, stepId]);
  if (error) return <ErrorState message={error} />;
  if (!blueprint) return <LoadingState label="Generating conventional blueprint..." />;
  return <><section className="mx-auto max-w-6xl"><Link to={`/review/${workflowId}`} className="text-sm font-semibold text-teal-700">← Back to step review</Link><p className="mt-8 text-sm font-semibold uppercase tracking-[0.22em] text-teal-700">03 / Automation blueprint</p><h1 className="mt-3 max-w-3xl font-display text-4xl font-semibold tracking-tight text-[#102a2c]">{blueprint.current_step.name}</h1><p className="mt-3 max-w-3xl rounded-xl bg-slate-100 px-4 py-3 text-sm font-medium leading-6 text-slate-700">This is the boring, deterministic fix: conventional automation with no new AI reasoning or autonomous judgment. Use Redesign when the work itself needs an agent-assisted rethink.</p><div className="mt-8 grid gap-4 rounded-3xl border border-slate-200 bg-white p-6 lg:grid-cols-2"><ComparisonColumn label="Before" title={blueprint.current_step.name} text={blueprint.current_step.description} /><ComparisonColumn label="After · automation blueprint" title={mechanismDescription(blueprint.mechanism_type)} text={[blueprint.trigger_condition, blueprint.rationale].join(". ")} /></div><div className="mt-8 grid gap-4 sm:grid-cols-3"><Info label="How it gets automated" value={mechanismDescription(blueprint.mechanism_type)} /><Info label="What starts it" value={blueprint.trigger_condition} /><Info label="Why this approach fits" value={blueprint.rationale} /></div><div className="mt-8"><WorkflowDiagram diagram={blueprint.diagram} /></div></section><ScreenChat context={storedScreenContext(workflowId, stepId, blueprint)} /></>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">{label}</p><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700">{textBullets(value).map((item, index) => <li key={`${label}-${index}`} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-teal-600" />{item}</li>)}</ul></div>; }
function mechanismDescription(value: AutomationBlueprint["mechanism_type"]): string { const definitions = { rpa: "RPA (Robotic Process Automation) — a bot that mimics manual clicks and data entry across existing systems, with no new AI reasoning involved.", rules_engine: "Rules engine — deterministic if/then logic that applies configured controls consistently, with no new AI reasoning involved.", scheduled_job: "Scheduled job — a predictable background task that runs on a fixed timetable, with no new AI reasoning involved.", existing_stp_extension: "Existing STP extension — a controlled addition to the current straight-through-processing path, with no new AI reasoning involved." }; return definitions[value]; }
function ComparisonColumn({ label, title, text }: { label: string; title: string; text: string }) { return <div className={`rounded-2xl p-5 ${label === "Before" ? "bg-slate-50" : "bg-[#e4eee9]"}`}><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-700">{label}</p><h2 className="mt-2 font-display text-xl font-semibold text-[#102a2c]">{title}</h2><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700">{textBullets(text).map((item, index) => <li key={`${label}-${index}`} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-teal-600" />{item}</li>)}</ul></div>; }
function LoadingState({ label }: { label: string }) { return <section className="rounded-3xl border border-slate-200 bg-white p-10 text-center text-slate-500">{label}</section>; }
function ErrorState({ message }: { message: string }) { return <section className="rounded-3xl border border-red-200 bg-red-50 p-10 text-center text-red-700">{message}</section>; }
