import { useEffect, useState, type ReactNode } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { getAutomationBlueprint, getWorkflow } from "../api/workflows";
import { WorkflowDiagram } from "../components/WorkflowDiagram";
import { ScreenChat } from "../components/ScreenChat";
import type { AutomationBlueprint, StaticWorkflowDiagram } from "../types/workflow";
import { storedScreenContext, textBullets } from "../utils/workflow";

export function AutomationBlueprintPage() {
  const { workflowId, stepId } = useParams(); const [searchParams] = useSearchParams(); const [blueprint, setBlueprint] = useState<AutomationBlueprint | null>(null); const [error, setError] = useState("");
  useEffect(() => { if (!workflowId || !stepId) return; getWorkflow(workflowId).then((workflow) => { const saved = workflow.automation_blueprints?.find((item) => item.step_id === stepId); if (saved) return setBlueprint(saved); return getAutomationBlueprint(workflowId, stepId).then(setBlueprint); }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Blueprint load failed.")); }, [workflowId, stepId]);
  if (error) return <ErrorState message={error} />; if (!blueprint) return <LoadingState label="Loading conventional blueprint..." />;
  const backPath = searchParams.get("from") === "flow" ? `/redesigned-flow/${workflowId}` : `/review/${workflowId}`; const backLabel = searchParams.get("from") === "flow" ? "generated flow" : "step review"; const beforeDiagram = currentStepDiagram(blueprint.current_step.name); const stages = blueprint.diagram.nodes.filter((node) => node.node_type !== "input" && node.node_type !== "output");
  return <><section className="mx-auto max-w-6xl"><Link to={backPath} className="text-sm font-semibold text-brand">← Back to {backLabel}</Link><div className="mt-7"><Eyebrow>03 / Automation blueprint</Eyebrow><h1 className="mt-4 font-display text-4xl font-semibold tracking-tight text-ink">{blueprint.current_step.name}</h1><p className="mt-3 max-w-3xl text-slate-500">A straightforward, rules-led improvement. No new AI judgment is introduced.</p></div><section className="mt-8 rounded-[28px] border border-blue-100 bg-white p-6 shadow-card sm:p-8"><SectionHeading eyebrow="Before" title="Current process" /><CompactItems items={textBullets(blueprint.current_step.description).slice(0, 3)} /><div className="mt-6"><WorkflowDiagram diagram={beforeDiagram} /></div></section><section className="mt-6 rounded-[28px] border border-blue-100 bg-white p-6 shadow-card sm:p-8"><SectionHeading eyebrow="After" title={mechanismTitle(blueprint.mechanism_type)} /><CompactItems items={[...textBullets(blueprint.trigger_condition), ...textBullets(blueprint.rationale)].slice(0, 3)} /><div className="mt-6"><WorkflowDiagram diagram={blueprint.diagram} /></div></section><section className="mt-6"><SectionHeading eyebrow="Agents assigned" title="Who handles each stage" /><div className="mt-4 grid gap-3 md:grid-cols-3">{(stages.length ? stages : [{ id: "stage-1", label: "Workflow automation", node_type: "process" }]).map((stage, index) => <article key={stage.id} className="rounded-[22px] border border-blue-100 bg-white p-5 shadow-card"><span className="grid h-9 w-9 place-items-center rounded-full bg-brand-gradient text-xs font-bold text-white">{index + 1}</span><h3 className="mt-4 font-display font-semibold text-ink">{index === 0 ? (blueprint.agent_name ?? contextualAgentName(blueprint.current_step.name)) : agentName(stage.label, index)}</h3><p className="mt-2 text-sm leading-5 text-slate-600">{agentDescription(stage.label, blueprint)}</p></article>)}</div></section><section className="mt-6 rounded-[24px] bg-brand-radial p-6 text-white shadow-float"><SectionHeading light eyebrow="Advantages" title="What improves" /><CompactItems items={advantages(blueprint).slice(0, 4)} light /></section></section><ScreenChat context={storedScreenContext(workflowId, stepId, blueprint)} /></>;
}
function currentStepDiagram(name: string): StaticWorkflowDiagram { return { nodes: [{ id: "current-input", label: "Case received", node_type: "input" }, { id: "current-step", label: name, node_type: "process" }, { id: "current-output", label: "Manual outcome", node_type: "output" }], edges: [{ source: "current-input", target: "current-step" }, { source: "current-step", target: "current-output" }] }; }
function mechanismTitle(value: AutomationBlueprint["mechanism_type"]): string { return ({ rpa: "Robotic Process Automation (RPA) handles the clicks", rules_engine: "Rules apply the decision consistently", scheduled_job: "A scheduled task runs the work", existing_stp_extension: "The existing straight-through processing path is extended" })[value]; }
function agentName(label: string, index: number): string { const names = ["Validation Bot", "Control Rules Agent", "Routing Agent", "Audit Recorder"]; return names[index] ?? `${label} Agent`; }
function contextualAgentName(stepName: string): string { const text = stepName.toLowerCase(); if (text.includes("match") || text.includes("reconcil")) return "Reconciliation Bot"; if (text.includes("exception") || text.includes("escalat")) return "Routing Agent"; if (text.includes("complete") || text.includes("validat")) return "Validation Bot"; return "Workflow Automation Agent"; }
function agentDescription(label: string, blueprint: AutomationBlueprint): string { return `${label} is checked against the configured trigger and recorded for the next stage. ${textBullets(blueprint.rationale)[0] ?? "The result is consistent and easy to review."}`; }
function advantages(blueprint: AutomationBlueprint): string[] { return [`Less manual work when ${blueprint.trigger_condition.toLowerCase()}`, "The same rules are applied every time", "A clear record supports audit and review", "Exceptions remain visible to the operations team"]; }
function SectionHeading({ eyebrow, title, light = false }: { eyebrow: string; title: string; light?: boolean }) { return <div><Eyebrow light={light}>{eyebrow}</Eyebrow><h2 className={`mt-2 font-display text-2xl font-semibold ${light ? "text-white" : "text-ink"}`}>{title}</h2></div>; }
function CompactItems({ items, light = false }: { items: string[]; light?: boolean }) { return <ul className="mt-4 grid gap-2 sm:grid-cols-2">{items.filter(Boolean).map((item, index) => <li key={`${item}-${index}`} className={`flex gap-3 rounded-2xl p-3 text-sm leading-5 ${light ? "bg-white/10 text-blue-100" : "bg-cloud text-slate-600"}`}><span className={`mt-1 grid h-4 w-4 shrink-0 place-items-center rounded-full text-[10px] font-bold ${light ? "bg-white/20 text-white" : "bg-blue-100 text-brand"}`}>✓</span>{item}</li>)}</ul>; }
function Eyebrow({ children, light = false }: { children: ReactNode; light?: boolean }) { return <span className={`inline-flex rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-[0.16em] ${light ? "bg-white/15 text-blue-100" : "bg-blue-50 text-brand"}`}>{children}</span>; }
function LoadingState({ label }: { label: string }) { return <section className="rounded-[28px] border border-blue-100 bg-white p-10 text-center text-slate-500 shadow-card">{label}</section>; }
function ErrorState({ message }: { message: string }) { return <section className="rounded-[28px] border border-red-200 bg-red-50 p-10 text-center text-red-700">{message}</section>; }
