import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { CartesianGrid, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";
import { getAnalyzedWorkflows } from "../api/workflows";
import { riskLabel, riskScore } from "../utils/workflow";
import type { Verdict, Workflow } from "../types/workflow";

type PortfolioPoint = { workflow: Workflow; x: number; y: number; z: number; automate: number; redesign: number; leave: number };

const verdictColors: Record<Verdict, string> = { automate: "#198754", redesign: "#d97706", leave_as_is: "#64748b" };

export function DashboardPage() {
  const [workflows, setWorkflows] = useState<Workflow[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { getAnalyzedWorkflows().then(setWorkflows).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Portfolio data failed.")); }, []);
  const points = workflows.map(toPoint);
  const totalSteps = workflows.reduce((sum, workflow) => sum + workflow.steps.length, 0);
  const highRisk = workflows.reduce((sum, workflow) => sum + workflow.scores.filter((score) => riskLabel(riskScore(score)) === "High").length, 0);
  const automate = workflows.reduce((sum, workflow) => sum + workflow.scores.filter((score) => score.verdict === "automate").length, 0);

  if (error) return <section className="rounded-3xl bg-red-50 p-8 text-red-700">{error}</section>;
  if (!workflows.length) return <section className="mx-auto max-w-3xl rounded-3xl border border-slate-200 bg-white p-10 text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-teal-700">04 / Portfolio view</p><h1 className="mt-4 font-display text-3xl font-semibold text-[#102a2c]">No analyzed workflows yet</h1><p className="mt-4 text-slate-500">Score a workflow first to place it on the complexity and exception grid.</p><Link to="/" className="mt-7 inline-flex rounded-xl bg-[#102a2c] px-5 py-3 text-sm font-bold text-white">Analyze a workflow</Link></section>;

  return <section className="mx-auto max-w-7xl"><div className="mb-10 flex flex-col justify-between gap-5 border-b border-slate-200 pb-8 sm:flex-row sm:items-end"><div><p className="mb-3 text-sm font-semibold uppercase tracking-[0.22em] text-teal-700">04 / Portfolio view</p><h1 className="font-display text-4xl font-semibold tracking-tight text-[#102a2c]">Where the book carries friction.</h1><p className="mt-3 max-w-2xl text-slate-500">Complexity is average judgment need; exception exposure is average compliance sensitivity. Larger points represent more steps.</p></div><span className="rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-semibold text-emerald-800">Live portfolio data</span></div>
    <div className="mb-6 grid gap-3 sm:grid-cols-3"><Metric label="Analyzed workflows" value={workflows.length} /><Metric label="Scored steps" value={totalSteps} /><Metric label="High-risk steps" value={highRisk} detail={`${automate} conventional automation candidate${automate === 1 ? "" : "s"}`} /></div>
    <div className="grid gap-6 lg:grid-cols-[1.4fr_0.6fr]"><article className="rounded-3xl border border-slate-200 bg-white p-5 sm:p-7"><div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="font-display text-xl font-semibold text-[#102a2c]">Complexity / exception grid</h2><p className="mt-1 text-sm text-slate-500">Each point is one analyzed workflow.</p></div><div className="text-right text-xs text-slate-400">Y: compliance sensitivity<br />X: judgment need</div></div><div className="h-[390px] w-full"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{ top: 18, right: 20, bottom: 26, left: 6 }}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis type="number" dataKey="x" domain={[1, 5]} name="Judgment need" tick={{ fontSize: 11 }} /><YAxis type="number" dataKey="y" domain={[1, 5]} name="Compliance sensitivity" tick={{ fontSize: 11 }} /><ZAxis type="number" dataKey="z" range={[100, 700]} /><Tooltip cursor={{ strokeDasharray: "3 3" }} content={<GridTooltip />} /><Scatter data={points} fill="#0f766e" /></ScatterChart></ResponsiveContainer></div></article><aside className="space-y-4">{points.map((point) => <Link key={point.workflow.workflow_id} to={`/review/${point.workflow.workflow_id}`} className="block rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:border-teal-300"><div className="flex items-start justify-between gap-3"><h3 className="font-display font-semibold text-[#102a2c]">{point.workflow.name}</h3><span className="text-xs font-semibold text-teal-700">{point.workflow.steps.length} steps</span></div><div className="mt-4 flex gap-2 text-[11px] font-semibold"><span className="rounded-full bg-emerald-50 px-2 py-1 text-emerald-700">{point.automate} automate</span><span className="rounded-full bg-amber-50 px-2 py-1 text-amber-700">{point.redesign} redesign</span><span className="rounded-full bg-slate-100 px-2 py-1 text-slate-600">{point.leave} as-is</span></div></Link>)}</aside></div></section>;
}

function toPoint(workflow: Workflow): PortfolioPoint { const scores = workflow.scores; const average = (key: "judgment_need" | "compliance_sensitivity") => scores.reduce((sum, score) => sum + score.scores[key], 0) / Math.max(scores.length, 1); return { workflow, x: Number(average("judgment_need").toFixed(2)), y: Number(average("compliance_sensitivity").toFixed(2)), z: workflow.steps.length, automate: scores.filter((score) => score.verdict === "automate").length, redesign: scores.filter((score) => score.verdict === "redesign").length, leave: scores.filter((score) => score.verdict === "leave_as_is").length }; }
function Metric({ label, value, detail }: { label: string; value: number; detail?: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs uppercase tracking-[0.16em] text-slate-400">{label}</p><p className="mt-2 font-display text-3xl font-semibold text-[#102a2c]">{value}</p>{detail && <p className="mt-1 text-xs text-slate-500">{detail}</p>}</div>; }
function GridTooltip({ active, payload }: { active?: boolean; payload?: Array<{ payload: PortfolioPoint }> }) { if (!active || !payload?.[0]) return null; const point = payload[0].payload; return <div className="rounded-xl border border-slate-200 bg-white p-3 text-xs shadow-lg"><p className="font-semibold text-[#102a2c]">{point.workflow.name}</p><p className="mt-1 text-slate-500">Judgment {point.x}/5 · Compliance {point.y}/5</p><p className="text-slate-500">{point.z} steps · {point.redesign} redesign</p></div>; }
