import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";
import { getAnalyzedWorkflows } from "../api/workflows";
import { VerdictBadge } from "../components/VerdictBadge";
import { riskScore } from "../utils/workflow";
import type { StepScore, Workflow } from "../types/workflow";

type PortfolioPoint = { workflow: Workflow; x: number; y: number; z: number };

export function DashboardPage() {
  const [workflows, setWorkflows] = useState<Workflow[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { getAnalyzedWorkflows().then(setWorkflows).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Portfolio data failed.")); }, []);
  const allScores = workflows.flatMap((workflow) => workflow.scores);
  const verdicts = ["automate", "redesign", "leave_as_is"].map((verdict) => ({ verdict, count: allScores.filter((score) => score.verdict === verdict).length }));
  const averageRisk = allScores.length ? (allScores.reduce((sum, score) => sum + riskScore(score), 0) / allScores.length).toFixed(1) : "0.0";
  if (error) return <section className="rounded-[24px] bg-red-50 p-8 text-red-700">{error}</section>;
  if (!workflows.length) return <EmptyDashboard />;
  return <section className="mx-auto max-w-7xl">
    <div className="relative overflow-hidden rounded-[28px] bg-brand-radial px-7 py-8 text-white shadow-float sm:px-10 sm:py-10">
      <div className="relative z-10 max-w-2xl"><Eyebrow light>Portfolio command center</Eyebrow><h1 className="mt-5 font-display text-4xl font-semibold tracking-tight sm:text-5xl">See where the book carries friction.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-blue-100 sm:text-base">A decision view for the workflows that deserve attention, conventional automation, or a safer redesign.</p></div>
      <div className="pointer-events-none absolute -right-16 -top-24 h-72 w-72 rounded-full bg-brand-soft/30 blur-3xl" />
      <div className="relative z-10 mt-8 flex flex-wrap items-center gap-3"><span className="rounded-full bg-white/15 px-4 py-2 text-xs font-semibold text-white backdrop-blur">{workflows.length} workflows live</span><span className="rounded-full bg-white px-4 py-2 text-xs font-semibold text-brand">Decision engine synced</span></div>
    </div>
    <div className="-mt-6 relative z-20 grid gap-3 px-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Workflows analyzed" value={workflows.length} /><Metric label="Steps scored" value={workflows.reduce((sum, workflow) => sum + workflow.steps.length, 0)} /><Metric label="Average risk" value={`${averageRisk}/5`} /><div className="rounded-[22px] border border-blue-100 bg-white p-4 shadow-card"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Verdict mix</p><div className="mt-2 h-14"><ResponsiveContainer width="100%" height="100%"><BarChart data={verdicts}><Bar dataKey="count" fill="#1e5fff" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></div><div className="flex justify-between text-[10px] capitalize text-slate-500">{verdicts.map((item) => <span key={item.verdict}>{item.verdict.replace("_", " ")} {item.count}</span>)}</div></div></div>
    <div className="mt-10"><div className="mb-5 flex items-end justify-between gap-4"><div><Eyebrow>Workflow book</Eyebrow><h2 className="mt-2 font-display text-2xl font-semibold">One clear signal per workflow</h2></div><span className="hidden text-xs text-slate-500 sm:block">AI fit is the headline metric</span></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{workflows.map((workflow) => <WorkflowCard key={workflow.workflow_id} workflow={workflow} />)}</div></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_0.7fr]"><article className="rounded-[24px] border border-blue-100 bg-white p-5 shadow-card sm:p-7"><div className="mb-5"><Eyebrow>Portfolio map</Eyebrow><h2 className="mt-2 font-display text-xl font-semibold">Complexity / exception exposure</h2><p className="mt-1 text-sm text-slate-500">Each point is a workflow. Larger points contain more steps.</p></div><div className="h-[330px]"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{ top: 12, right: 16, bottom: 18, left: 0 }}><CartesianGrid stroke="#e5edfb" strokeDasharray="4 4" /><XAxis type="number" dataKey="x" name="Judgment" domain={[0, 5]} tick={{ fill: "#64748b", fontSize: 11 }} /><YAxis type="number" dataKey="y" name="Compliance" domain={[0, 5]} tick={{ fill: "#64748b", fontSize: 11 }} /><ZAxis type="number" dataKey="z" range={[80, 420]} /><Tooltip content={<GridTooltip />} /><Scatter data={workflows.map(toPoint)} fill="#1e5fff" /></ScatterChart></ResponsiveContainer></div></article><article className="rounded-[24px] bg-[#0d1834] p-7 text-white shadow-card"><Eyebrow light>How to read it</Eyebrow><h2 className="mt-3 font-display text-2xl font-semibold">Make the next move defensible.</h2><p className="mt-4 text-sm leading-6 text-blue-100">High judgment and high compliance exposure are where a bounded redesign earns its keep. Low-risk repetition belongs with rules, not a creative agent.</p><div className="mt-8 space-y-3"><Legend color="bg-blue-400" label="Automate" detail="Repeatable work" /><Legend color="bg-violet-400" label="Redesign" detail="Judgment with controls" /><Legend color="bg-slate-400" label="Leave as-is" detail="Keep the current path" /></div></article></div>
  </section>;
}

function WorkflowCard({ workflow }: { workflow: Workflow }) { const scores = workflow.scores; const primary = scores.slice().sort((a, b) => b.scores.ai_suitability - a.scores.ai_suitability)[0]; const averageAi = scores.length ? (scores.reduce((sum, score) => sum + score.scores.ai_suitability, 0) / scores.length).toFixed(1) : "0.0"; const redesign = scores.filter((score) => score.verdict === "redesign").length; const automate = scores.filter((score) => score.verdict === "automate").length; return <Link to={`/review/${workflow.workflow_id}`} className="group rounded-[24px] border border-blue-100 bg-white p-6 shadow-card transition hover:-translate-y-1 hover:shadow-float focus:outline-none focus:ring-4 focus:ring-blue-200"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-brand-gradient text-sm font-bold text-white ring-4 ring-blue-50">{workflow.name.slice(0, 1)}</span><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Workflow</p><h3 className="mt-1 font-display text-lg font-semibold text-ink">{workflow.name.replaceAll("_", " ")}</h3></div></div>{primary && <VerdictBadge verdict={primary.verdict} />}</div><div className="mt-8 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Average AI fit</p><p className="mt-1 font-display text-6xl font-semibold tracking-tight text-brand">{averageAi}<span className="ml-1 text-xl text-slate-400">/5</span></p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">{workflow.steps.length} steps</span></div><div className="mt-6 grid grid-cols-3 gap-2 border-t border-slate-100 pt-4 text-xs"><SmallMetric label="As-is" value={scores.filter((score) => score.verdict === "leave_as_is").length} /><SmallMetric label="Automate" value={automate} /><SmallMetric label="Redesign" value={redesign} /></div><p className="mt-5 text-xs font-semibold text-brand transition group-hover:text-brand-deep">Open workflow review <span aria-hidden="true">↗</span></p></Link>; }
function SmallMetric({ label, value }: { label: string; value: number }) { return <div><p className="text-slate-400">{label}</p><p className="mt-1 font-display text-lg font-semibold text-ink">{value}</p></div>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-[22px] border border-blue-100 bg-white p-5 shadow-card"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">{label}</p><p className="mt-2 font-display text-3xl font-semibold text-ink">{value}</p></div>; }
function Eyebrow({ children, light = false }: { children: ReactNode; light?: boolean }) { return <span className={`inline-flex rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-[0.16em] ${light ? "bg-white/15 text-blue-100" : "bg-blue-50 text-brand"}`}>{children}</span>; }
function Legend({ color, label, detail }: { color: string; label: string; detail: string }) { return <div className="flex items-center gap-3"><span className={`h-3 w-3 rounded-full ${color}`} /><div><p className="text-sm font-semibold">{label}</p><p className="text-xs text-blue-200">{detail}</p></div></div>; }
function toPoint(workflow: Workflow): PortfolioPoint { const average = (key: "judgment_need" | "compliance_sensitivity") => workflow.scores.reduce((sum, score) => sum + score.scores[key], 0) / Math.max(workflow.scores.length, 1); return { workflow, x: Number(average("judgment_need").toFixed(2)), y: Number(average("compliance_sensitivity").toFixed(2)), z: workflow.steps.length }; }
function GridTooltip({ active, payload }: { active?: boolean; payload?: Array<{ payload: PortfolioPoint }> }) { if (!active || !payload?.[0]) return null; const point = payload[0].payload; return <div className="rounded-2xl border border-blue-100 bg-white p-3 text-xs shadow-float"><p className="font-semibold text-ink">{point.workflow.name.replaceAll("_", " ")}</p><p className="mt-1 text-slate-500">Judgment {point.x}/5 · Compliance {point.y}/5</p><p className="text-slate-500">{point.z} steps</p></div>; }
function EmptyDashboard() { return <section className="mx-auto max-w-3xl rounded-[28px] border border-blue-100 bg-white p-10 text-center shadow-card"><Eyebrow>Portfolio view</Eyebrow><h1 className="mt-4 font-display text-3xl font-semibold">No analyzed workflows yet</h1><p className="mt-4 text-slate-500">Score a workflow first to place it on the portfolio map.</p><Link to="/" className="mt-7 inline-flex rounded-full bg-brand px-5 py-3 text-sm font-bold text-white">Analyze a workflow</Link></section>; }
