import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getWorkflow } from "../api/workflows";
import { VerdictBadge } from "../components/VerdictBadge";
import type { Workflow } from "../types/workflow";
import { textBullets } from "../utils/workflow";

export function RedesignedFlowPage() {
  const { workflowId } = useParams(); const [workflow, setWorkflow] = useState<Workflow | null>(null); const [error, setError] = useState("");
  useEffect(() => { if (workflowId) getWorkflow(workflowId).then(setWorkflow).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Flow load failed.")); }, [workflowId]);
  if (error) return <p className="rounded-[24px] bg-red-50 p-6 text-red-700">{error}</p>;
  if (!workflow) return <p className="rounded-[28px] border border-blue-100 bg-white p-10 text-center text-slate-500 shadow-card">Loading generated flow...</p>;
  const generatedSteps = workflow.steps.filter((step) => workflow.automation_blueprints?.some((item) => item.step_id === step.step_id) || workflow.redesign_proposals?.some((item) => item.step_id === step.step_id));
  return <section className="mx-auto max-w-6xl"><Link to={`/review/${workflow.workflow_id}`} className="text-sm font-semibold text-brand">← Back to step review</Link><div className="mt-7"><span className="inline-flex rounded-full bg-blue-50 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.18em] text-brand">05 / Generated flow</span><h1 className="mt-4 font-display text-4xl font-semibold tracking-tight text-ink">{workflow.name.replaceAll("_", " ")}</h1><p className="mt-3 text-slate-500">A quick scan of generated recommendations. Open any step for the complete proposal.</p></div>{generatedSteps.length === 0 ? <div className="mt-8 rounded-[28px] border border-dashed border-blue-200 bg-white p-10 text-center text-slate-500 shadow-card">No generated outputs yet. Return to step review to generate one.</div> : <div className="mt-8 space-y-4">{generatedSteps.map((step, index) => { const score = workflow.scores.find((item) => item.step_id === step.step_id); const blueprint = workflow.automation_blueprints?.find((item) => item.step_id === step.step_id); const proposal = workflow.redesign_proposals?.find((item) => item.step_id === step.step_id); if (!score) return null; const before = textBullets(step.description).slice(0, 2); const after = blueprint ? [...textBullets(blueprint.trigger_condition), ...textBullets(blueprint.rationale)].slice(0, 2) : [...textBullets(proposal?.proposed_design ?? ""), ...textBullets(proposal?.expected_benefits?.[0] ?? "")].slice(0, 2); const detailPath = blueprint ? `/automation/${workflow.workflow_id}/${step.step_id}?from=flow` : `/redesign/${workflow.workflow_id}/${step.step_id}?from=flow`; return <article key={step.step_id} className="rounded-[24px] border border-blue-100 bg-white p-5 shadow-card sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-blue-50 text-xs font-bold text-brand">{String(index + 1).padStart(2, "0")}</span><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Generated step</p><h2 className="mt-1 font-display text-xl font-semibold text-ink">{step.name}</h2></div></div><VerdictBadge verdict={score.verdict} /></div><div className="mt-5 grid gap-3 md:grid-cols-2"><SummaryBlock label="Before" items={before} /><SummaryBlock label="After" items={after} /></div><Link to={detailPath} className="mt-5 inline-flex rounded-full bg-brand px-4 py-2 text-xs font-bold text-white">Open full {blueprint ? "blueprint" : "redesign"} ↗</Link></article>; })}</div>}</section>;
}

function SummaryBlock({ label, items }: { label: string; items: string[] }) { return <div className="rounded-2xl bg-cloud p-4"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-brand">{label}</p><ul className="mt-2 space-y-2 text-sm leading-5 text-slate-600">{items.filter(Boolean).map((item, index) => <li key={`${label}-${index}`} className="flex gap-2"><span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-brand" />{item}</li>)}</ul></div>; }
