import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getWorkflow } from "../api/workflows";
import type { Workflow } from "../types/workflow";
import { textBullets } from "../utils/workflow";

export function RedesignedFlowPage() {
  const { workflowId } = useParams();
  const [workflow, setWorkflow] = useState<Workflow | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { if (workflowId) getWorkflow(workflowId).then(setWorkflow).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Flow load failed.")); }, [workflowId]);
  if (error) return <p className="rounded-2xl bg-red-50 p-6 text-red-700">{error}</p>;
  if (!workflow) return <p className="rounded-3xl border border-slate-200 bg-white p-10 text-center text-slate-500">Loading generated flow...</p>;
  const generatedSteps = workflow.steps.filter((step) => workflow.automation_blueprints?.some((item) => item.step_id === step.step_id) || workflow.redesign_proposals?.some((item) => item.step_id === step.step_id));
  return <section className="mx-auto max-w-6xl"><Link to={`/review/${workflow.workflow_id}`} className="text-sm font-semibold text-teal-700">← Back to step review</Link><div className="mt-8 border-b border-slate-200 pb-8"><p className="text-sm font-semibold uppercase tracking-[0.22em] text-teal-700">05 / Redesigned flow</p><h1 className="mt-3 font-display text-4xl font-semibold tracking-tight text-[#102a2c]">{workflow.name}</h1><p className="mt-3 text-slate-500">A browseable view of every step with a generated automation blueprint or agent-first redesign.</p></div>{generatedSteps.length === 0 ? <div className="mt-8 rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No generated outputs yet. Return to step review to generate one.</div> : <div className="mt-8 space-y-5">{generatedSteps.map((step, index) => { const score = workflow.scores.find((item) => item.step_id === step.step_id); const blueprint = workflow.automation_blueprints?.find((item) => item.step_id === step.step_id); const proposal = workflow.redesign_proposals?.find((item) => item.step_id === step.step_id); return <article key={step.step_id} className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-teal-700">Step {index + 1}</p><h2 className="mt-1 font-display text-2xl font-semibold text-[#102a2c]">{step.name}</h2></div><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${blueprint ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{blueprint ? "automate · blueprint" : "redesign · proposal"}</span></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><Column label="Original step" title={step.name} items={[step.description]} /><Column label={blueprint ? "Generated automation" : "Generated redesign"} title={blueprint ? blueprint.mechanism_type.replaceAll("_", " ") : "Agent-first design"} items={blueprint ? [blueprint.trigger_condition, blueprint.rationale] : [proposal?.proposed_design ?? "", ...(proposal?.agent_responsibilities ?? []), ...(proposal?.human_controls ?? [])]} /></div><Link to={blueprint ? `/automation/${workflow.workflow_id}/${step.step_id}` : `/redesign/${workflow.workflow_id}/${step.step_id}`} className="mt-5 inline-flex text-sm font-semibold text-teal-700">Open full generated output →</Link>{score && <p className="mt-3 text-xs text-slate-400">Decision: {score.verdict} · judgment need {score.scores.judgment_need}/5 · compliance sensitivity {score.scores.compliance_sensitivity}/5</p>}</article>; })}</div>}</section>;
}

function Column({ label, title, items }: { label: string; title: string; items: string[] }) { return <div className={`rounded-2xl p-5 ${label === "Original step" ? "bg-slate-50" : "bg-[#e4eee9]"}`}><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-700">{label}</p><h3 className="mt-2 font-display text-lg font-semibold text-[#102a2c]">{title}</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700">{items.flatMap(textBullets).filter(Boolean).map((item, index) => <li key={`${label}-${index}`} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-teal-600" />{item}</li>)}</ul></div>; }
