import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import { Link, useParams } from "react-router-dom";
import { getRedesignProposal, getWorkflow } from "../api/workflows";
import { WorkflowDiagram } from "../components/WorkflowDiagram";
import { ScreenChat } from "../components/ScreenChat";
import type { RedesignProposal, StaticWorkflowDiagram } from "../types/workflow";
import { storedScreenContext, textBullets } from "../utils/workflow";

export function RedesignProposalPage() {
  const { workflowId, stepId } = useParams(); const [proposal, setProposal] = useState<RedesignProposal | null>(null); const [error, setError] = useState("");
  useEffect(() => { if (!workflowId || !stepId) return; getWorkflow(workflowId).then((workflow) => { const saved = workflow.redesign_proposals?.find((item) => item.step_id === stepId); if (saved) return setProposal(saved); return getRedesignProposal(workflowId, stepId).then(setProposal); }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Redesign load failed.")); }, [workflowId, stepId]);
  if (error) return <p className="rounded-[24px] bg-red-50 p-6 text-red-700">{error}</p>;
  if (!proposal) return <p className="rounded-[28px] border border-blue-100 bg-white p-10 text-center text-slate-500 shadow-card">Loading agent-first redesign...</p>;
  const beforeDiagram = currentStepDiagram(proposal.current_step.name, proposal.current_step.description);
  return <><section className="mx-auto max-w-6xl"><Link to={`/review/${workflowId}`} className="text-sm font-semibold text-brand">← Back to step review</Link><div className="mt-7"><Eyebrow>03 / Redesign proposal</Eyebrow><h1 className="mt-4 font-display text-4xl font-semibold tracking-tight text-ink">{proposal.current_step.name}</h1><p className="mt-3 max-w-3xl text-slate-500">A bounded agent-first redesign with clear human control points.</p></div><section className="mt-8 rounded-[28px] border border-blue-100 bg-white p-6 shadow-card sm:p-8"><SectionHeading eyebrow="Before" title="Current process" /><CompactList text={proposal.current_step.description} max={4} /><div className="mt-6"><WorkflowDiagram diagram={beforeDiagram} /></div></section><section className="mt-6 rounded-[28px] border border-blue-100 bg-white p-6 shadow-card sm:p-8"><SectionHeading eyebrow="After" title="Agent-first redesign" /><CompactList text={proposal.proposed_design} max={4} /><div className="mt-6"><WorkflowDiagram diagram={proposal.diagram} /></div></section><div className="mt-6 grid gap-4 md:grid-cols-3"><ListCard title="Problem to solve" items={textBullets(proposal.problem_statement).slice(0, 3)} /><ListCard title="Agent responsibilities" items={proposal.agent_responsibilities.slice(0, 4)} /><ListCard title="Human controls" items={proposal.human_controls.slice(0, 4)} /></div><div className="mt-6 rounded-[24px] border border-blue-100 bg-white p-6 shadow-card"><SectionHeading eyebrow="Expected outcome" title="Why this helps" /><CompactItems items={proposal.expected_benefits.slice(0, 4)} /></div></section><ScreenChat context={storedScreenContext(workflowId, stepId, proposal)} /></>;
}

function currentStepDiagram(name: string, description: string): StaticWorkflowDiagram { return { nodes: [{ id: "current-input", label: "Case received", node_type: "input" }, { id: "current-step", label: name, node_type: "process" }, { id: "current-output", label: "Operational outcome", node_type: "output" }], edges: [{ source: "current-input", target: "current-step" }, { source: "current-step", target: "current-output", label: textBullets(description)[0] }] }; }
function SectionHeading({ eyebrow, title }: { eyebrow: string; title: string }) { return <div><Eyebrow>{eyebrow}</Eyebrow><h2 className="mt-2 font-display text-2xl font-semibold text-ink">{title}</h2></div>; }
function CompactList({ text, max }: { text: string; max: number }) { return <CompactItems items={textBullets(text).slice(0, max)} />; }
function CompactItems({ items }: { items: string[] }) { return <ul className="mt-4 grid gap-2 sm:grid-cols-2">{items.filter(Boolean).map((item, index) => <li key={`${item}-${index}`} className="flex gap-3 rounded-2xl bg-cloud p-3 text-sm leading-5 text-slate-600"><span className="mt-1 grid h-4 w-4 shrink-0 place-items-center rounded-full bg-blue-100 text-[10px] font-bold text-brand">✓</span>{item}</li>)}</ul>; }
function ListCard({ title, items }: { title: string; items: string[] }) { return <article className="rounded-[24px] border border-blue-100 bg-white p-5 shadow-card"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-brand">{title}</p><CompactItems items={items} /></article>; }
function Eyebrow({ children }: { children: ReactNode }) { return <span className="inline-flex rounded-full bg-blue-50 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.16em] text-brand">{children}</span>; }
