import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getExecutiveReport } from "../api/workflows";
import type { ExecutiveReport, Verdict } from "../types/workflow";

const verdictStyles: Record<Verdict, string> = { automate: "bg-emerald-100 text-emerald-800", redesign: "bg-amber-100 text-amber-800", leave_as_is: "bg-slate-100 text-slate-700" };

export function ReportPage() {
  const { workflowId } = useParams();
  const [report, setReport] = useState<ExecutiveReport | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { if (workflowId) getExecutiveReport(workflowId).then(setReport).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Report failed.")); }, [workflowId]);
  if (error) return <p className="rounded-2xl bg-red-50 p-6 text-red-700">{error}</p>;
  if (!report) return <p className="rounded-3xl border border-slate-200 bg-white p-10 text-center text-slate-500">Compiling executive report...</p>;
  return <section className="mx-auto max-w-6xl print:max-w-none"><div className="flex flex-wrap items-start justify-between gap-5"><div><Link to={`/review/${report.workflow_id}`} className="text-sm font-semibold text-teal-700 print:hidden">← Back to review</Link><p className="mt-8 text-sm font-semibold uppercase tracking-[0.22em] text-teal-700">06 / Executive report</p><h1 className="mt-3 font-display text-4xl font-semibold tracking-tight text-[#102a2c]">{report.workflow_name}</h1></div><button type="button" onClick={() => window.print()} className="rounded-xl bg-[#102a2c] px-4 py-2.5 text-sm font-semibold text-white print:hidden">Print / Save PDF</button></div><div className="mt-8 rounded-3xl bg-[#102a2c] p-7 text-white"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#f2c14e]">Recommendation</p><h2 className="mt-3 font-display text-3xl font-semibold">{report.headline_verdict}</h2><p className="mt-4 max-w-4xl text-sm leading-7 text-slate-200">{report.executive_summary}</p></div><div className="mt-6 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Steps", report.metrics.total_steps], ["As-is", report.metrics.leave_as_is], ["Automate", report.metrics.automate], ["Redesign", report.metrics.redesign], ["AI fit", `${report.metrics.average_ai_suitability}/5`], ["Compliance", `${report.metrics.average_compliance_sensitivity}/5`]].map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 font-display text-2xl font-semibold text-[#102a2c]">{value}</p></div>)}</div><div className="mt-8 grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><article className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-display text-xl font-semibold text-[#102a2c]">Key recommendations</h2><ul className="mt-4 space-y-3">{report.key_recommendations.map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-slate-600"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-teal-600" />{item}</li>)}</ul></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-display text-xl font-semibold text-[#102a2c]">Step-level decisions</h2><div className="mt-4 divide-y divide-slate-100">{report.step_summaries.map((item) => <div key={item.step.step_id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm font-semibold text-[#102a2c]">{item.step.name}</p><p className="text-xs text-slate-500">{item.score.reasoning}</p></div><span className={`shrink-0 rounded-full px-3 py-1 text-xs font-semibold ${verdictStyles[item.score.verdict]}`}>{item.score.verdict.replaceAll("_", " ")}</span></div>)}</div></article></div></section>;
}
