import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getExecutiveReport } from "../api/workflows";
import { riskExplanation, riskScore, textBullets } from "../utils/workflow";
import type { ExecutiveReport, Verdict } from "../types/workflow";

const verdictStyles: Record<Verdict, string> = { automate: "bg-blue-50 text-blue-700 ring-1 ring-blue-200", redesign: "bg-violet-50 text-violet-700 ring-1 ring-violet-200", leave_as_is: "bg-slate-100 text-slate-700 ring-1 ring-slate-200" };

export function ReportPage() {
  const { workflowId } = useParams(); const [report, setReport] = useState<ExecutiveReport | null>(null); const [error, setError] = useState("");
  useEffect(() => { if (workflowId) getExecutiveReport(workflowId).then(setReport).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Report failed.")); }, [workflowId]);
  if (error) return <p className="rounded-[24px] bg-red-50 p-6 text-red-700">{error}</p>;
  if (!report) return <p className="rounded-[28px] border border-blue-100 bg-white p-10 text-center text-slate-500 shadow-card">Compiling executive report...</p>;
  const metrics = [["Steps", report.metrics.total_steps], ["As-is", report.metrics.leave_as_is], ["Automate", report.metrics.automate], ["Redesign", report.metrics.redesign], ["AI fit", `${report.metrics.average_ai_suitability}/5`], ["Compliance", `${report.metrics.average_compliance_sensitivity}/5`]];
  return <section className="mx-auto max-w-6xl print:max-w-none"><div className="flex flex-wrap items-start justify-between gap-5"><div><Link to={`/review/${report.workflow_id}`} className="text-sm font-semibold text-brand print:hidden">← Back to review</Link><p className="mt-8 inline-flex rounded-full bg-blue-50 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.18em] text-brand">Executive report</p><h1 className="mt-4 font-display text-4xl font-semibold tracking-tight text-ink">{report.workflow_name.replaceAll("_", " ")}</h1></div><button type="button" onClick={() => window.print()} className="rounded-full bg-[#0d1834] px-5 py-3 text-sm font-semibold text-white print:hidden">Print / Save PDF</button></div><div className="mt-8 rounded-[28px] bg-brand-radial p-7 text-white shadow-float sm:p-9"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-100">Recommendation</p><h2 className="mt-3 font-display text-3xl font-semibold">{report.headline_verdict}</h2><BulletList text={report.executive_summary} light /></div><div className="mt-6 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{metrics.map(([label, value]) => <div key={String(label)} className="rounded-[20px] border border-blue-100 bg-white p-4 shadow-card"><p className="text-xs uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 font-display text-2xl font-semibold text-ink">{value}</p></div>)}</div><div className="mt-8 rounded-[24px] border border-blue-100 bg-white p-6 shadow-card"><h2 className="font-display text-xl font-semibold text-ink">Key recommendations</h2><BulletItems items={report.key_recommendations} /></div><div className="mt-8 space-y-4"><h2 className="font-display text-2xl font-semibold text-ink">Step findings</h2>{report.step_summaries.map((summary) => { const risk = riskScore(summary.score); return <article key={summary.step.step_id} className="rounded-[24px] border border-blue-100 bg-white p-6 shadow-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.16em] text-brand">Step {summary.step.step_id}</p><h3 className="mt-1 font-display text-xl font-semibold text-ink">{summary.step.name}</h3></div><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${verdictStyles[summary.score.verdict]}`}>{summary.score.verdict.replaceAll("_", " ")}</span></div><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_220px]"><div><BulletList text={summary.score.reasoning} /></div><div className="rounded-[20px] bg-blue-50 p-4"><p className="text-xs uppercase tracking-wide text-brand">Risk / AI fit</p><p className="mt-1 font-display text-xl font-semibold text-ink">{risk}/5 · {summary.score.scores.ai_suitability}/5</p><p className="mt-2 text-xs leading-5 text-slate-600">{riskExplanation(summary.score)}</p></div></div></article>; })}</div></section>;
}

function BulletList({ text, light = false }: { text: string; light?: boolean }) { return <ul className={`mt-4 space-y-2 text-sm leading-6 ${light ? "text-blue-100" : "text-slate-600"}`}>{textBullets(text).map((item, index) => <li key={`${item}-${index}`} className="flex gap-3"><span className={`mt-2 h-1.5 w-1.5 shrink-0 rounded-full ${light ? "bg-blue-200" : "bg-brand"}`} />{item}</li>)}</ul>; }
function BulletItems({ items }: { items: string[] }) { return <ul className="mt-4 space-y-3">{items.flatMap(textBullets).map((item, index) => <li key={`${item}-${index}`} className="flex gap-3 text-sm leading-6 text-slate-600"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brand" />{item}</li>)}</ul>; }
