import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getExecutiveReport } from "../api/workflows";
import { riskExplanation, riskLabel, riskScore, textBullets } from "../utils/workflow";
import type { ExecutiveReport, Verdict } from "../types/workflow";

const verdictStyles: Record<Verdict, string> = { automate: "bg-emerald-100 text-emerald-800", redesign: "bg-amber-100 text-amber-800", leave_as_is: "bg-slate-100 text-slate-700" };

export function ReportPage() {
  const { workflowId } = useParams();
  const [report, setReport] = useState<ExecutiveReport | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { if (workflowId) getExecutiveReport(workflowId).then(setReport).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Report failed.")); }, [workflowId]);
  if (error) return <p className="rounded-2xl bg-red-50 p-6 text-red-700">{error}</p>;
  if (!report) return <p className="rounded-3xl border border-slate-200 bg-white p-10 text-center text-slate-500">Compiling executive report...</p>;
  return <section className="mx-auto max-w-6xl print:max-w-none"><div className="flex flex-wrap items-start justify-between gap-5"><div><Link to={`/review/${report.workflow_id}`} className="text-sm font-semibold text-teal-700 print:hidden">← Back to review</Link><p className="mt-8 text-sm font-semibold uppercase tracking-[0.22em] text-teal-700">06 / Executive report</p><h1 className="mt-3 font-display text-4xl font-semibold tracking-tight text-[#102a2c]">{report.workflow_name}</h1></div><button type="button" onClick={() => window.print()} className="rounded-xl bg-[#102a2c] px-4 py-2.5 text-sm font-semibold text-white print:hidden">Print / Save PDF</button></div><div className="mt-8 rounded-3xl bg-[#102a2c] p-7 text-white"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#f2c14e]">Recommendation</p><h2 className="mt-3 font-display text-3xl font-semibold">{report.headline_verdict}</h2><BulletList text={report.executive_summary} light /></div><div className="mt-6 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Steps", report.metrics.total_steps], ["As-is", report.metrics.leave_as_is], ["Automate", report.metrics.automate], ["Redesign", report.metrics.redesign], ["AI fit", `${report.metrics.average_ai_suitability}/5`], ["Compliance", `${report.metrics.average_compliance_sensitivity}/5`]].map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 font-display text-2xl font-semibold text-[#102a2c]">{value}</p></div>)}</div><div className="mt-8 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-display text-xl font-semibold text-[#102a2c]">Key recommendations</h2><BulletItems items={report.key_recommendations} /></div><div className="mt-8 space-y-4"><h2 className="font-display text-2xl font-semibold text-[#102a2c]">Step findings</h2>{report.step_summaries.map((summary) => { const risk = riskScore(summary.score); return <article key={summary.score.step_id} className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-display text-xl font-semibold text-[#102a2c]">{summary.step.name}</h3><span className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${verdictStyles[summary.score.verdict]}`}>{summary.score.verdict.replaceAll("_", " ")}</span></div><div><span className="rounded-xl bg-[#e4eee9] px-3 py-2 text-xs font-semibold text-teal-800">Risk {risk}/5 · {riskLabel(risk)}</span><p className="mt-2 max-w-xl text-xs leading-5 text-slate-500">{riskExplanation(summary.score)}</p></div></div><div className="mt-5"><p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-400">Reasoning</p><BulletList text={summary.score.reasoning} /></div></article>; })}</div></section>;
}

function BulletList({ text, light = false }: { text: string; light?: boolean }) { return <ul className={`mt-4 space-y-2 text-sm leading-6 ${light ? "text-slate-200" : "text-slate-600"}`}>{textBullets(text).map((item, index) => <li key={`${item}-${index}`} className="flex gap-3"><span className={`mt-2 h-1.5 w-1.5 shrink-0 rounded-full ${light ? "bg-[#f2c14e]" : "bg-teal-600"}`} />{item}</li>)}</ul>; }
function BulletItems({ items }: { items: string[] }) { return <ul className="mt-4 space-y-3">{items.flatMap(textBullets).map((item, index) => <li key={`${item}-${index}`} className="flex gap-3 text-sm leading-6 text-slate-600"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-teal-600" />{item}</li>)}</ul>; }
