import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { getWorkflow } from "../api/workflows";
import { VerdictBadge } from "../components/VerdictBadge";
import { WorkflowDiagram } from "../components/WorkflowDiagram";
import { ScreenChat } from "../components/ScreenChat";
import { ScoreTooltip } from "../components/ScoreTooltip";
import type { StepScore, Workflow } from "../types/workflow";
import { riskExplanation, riskLabel, riskScore, screenContext, textBullets } from "../utils/workflow";

export function StepReviewPage() {
  const { workflowId } = useParams(); const navigate = useNavigate();
  const [workflow, setWorkflow] = useState<Workflow | null>(null); const [selectedId, setSelectedId] = useState<string>(); const [view, setView] = useState<"steps" | "map">("steps"); const [error, setError] = useState("");
  useEffect(() => { if (!workflowId) return; getWorkflow(workflowId).then((loaded) => { setWorkflow(loaded); setSelectedId((current) => current ?? loaded.steps[0]?.step_id); sessionStorage.setItem("currentWorkflow", JSON.stringify(loaded)); }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Workflow load failed.")); }, [workflowId]);
  if (error) return <section className="rounded-[24px] bg-red-50 p-8 text-red-700">{error}</section>;
  if (!workflow || workflow.workflow_id !== workflowId) return <EmptyReview />;
  const selected = workflow.steps.find((step) => step.step_id === selectedId) ?? workflow.steps[0]; const score = workflow.scores.find((item) => item.step_id === selected.step_id);
  return <section className="mx-auto max-w-7xl"><div className="relative overflow-hidden rounded-[28px] bg-brand-radial px-7 py-8 text-white shadow-float sm:px-10"><div className="relative z-10 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><Eyebrow light>Step review · {workflow.steps.length} steps</Eyebrow><h1 className="mt-5 max-w-3xl font-display text-4xl font-semibold tracking-tight sm:text-5xl">{workflow.name.replaceAll("_", " ")}</h1><p className="mt-3 text-sm text-blue-100">One decision at a time, with the evidence behind it always in reach.</p></div>{score && <div className="rounded-[22px] border border-white/20 bg-white/10 p-4 backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-blue-100">Selected verdict</p><div className="mt-2"><VerdictBadge verdict={score.verdict} /></div></div>}</div><div className="pointer-events-none absolute -right-10 -top-20 h-64 w-64 rounded-full bg-brand-soft/30 blur-3xl" /></div>
    <div className="mt-6"><div className="inline-flex rounded-full border border-blue-100 bg-white p-1 shadow-card" role="tablist" aria-label="Step review view"><button type="button" role="tab" aria-selected={view === "steps"} onClick={() => setView("steps")} className={`rounded-full px-5 py-2.5 text-sm font-semibold transition ${view === "steps" ? "bg-brand text-white shadow" : "text-slate-500 hover:text-brand"}`}>Workflow Steps</button><button type="button" role="tab" aria-selected={view === "map"} onClick={() => setView("map")} className={`rounded-full px-5 py-2.5 text-sm font-semibold transition ${view === "map" ? "bg-brand text-white shadow" : "text-slate-500 hover:text-brand"}`}>Sequence Map</button></div></div>
    {view === "steps" ? <div className="mt-6 grid gap-6 lg:grid-cols-[280px_minmax(0,1fr)]"><aside className="space-y-3"><div className="flex items-center justify-between"><div><Eyebrow>Workflow steps</Eyebrow><p className="mt-2 text-xs text-slate-500">Select a step to inspect</p></div><span className="font-display text-sm font-semibold text-brand">{String(Number(selected.step_id)).padStart(2, "0")} / {workflow.steps.length}</span></div>{workflow.steps.map((step) => { const item = workflow.scores.find((entry) => entry.step_id === step.step_id); const active = step.step_id === selected.step_id; return <button key={step.step_id} type="button" onClick={() => setSelectedId(step.step_id)} className={`w-full cursor-pointer rounded-[20px] border p-4 text-left transition ${active ? "border-brand bg-white shadow-card ring-2 ring-blue-100" : "border-blue-100 bg-white/70 hover:border-blue-300 hover:bg-white"}`}><div className="flex items-center justify-between gap-3"><span className={`grid h-8 w-8 place-items-center rounded-full text-xs font-bold ${active ? "bg-brand text-white" : "bg-blue-50 text-brand"}`}>{String(Number(step.step_id)).padStart(2, "0")}</span>{item && <VerdictBadge verdict={item.verdict} />}</div><p className="mt-3 line-clamp-2 text-sm font-semibold text-ink">{step.name}</p></button>; })}</aside><div className="min-w-0"><StepDetail step={selected} score={score} onGenerate={() => score?.verdict === "automate" ? navigate(`/automation/${workflow.workflow_id}/${selected.step_id}`) : navigate(`/redesign/${workflow.workflow_id}/${selected.step_id}`)} /></div></div> : <div className="mt-6"><div className="mb-4 flex items-end justify-between gap-4"><div><Eyebrow>Sequence map</Eyebrow><h2 className="mt-2 font-display text-2xl font-semibold">How the work moves</h2></div><span className="text-xs text-slate-500">Click a node to inspect</span></div><WorkflowDiagram workflow={workflow} selectedStepId={selected.step_id} onStepSelect={setSelectedId} onWorkflowChange={(updated) => { setWorkflow(updated); sessionStorage.setItem("currentWorkflow", JSON.stringify(updated)); }} /></div>}
    <div className="mt-8 flex flex-wrap gap-3 rounded-[24px] border border-blue-100 bg-white p-5 shadow-card"><Link to={`/redesigned-flow/${workflow.workflow_id}`} className="rounded-full bg-brand px-4 py-2.5 text-sm font-semibold text-white">Browse generated flow ↗</Link><Link to={`/report/${workflow.workflow_id}`} className="rounded-full bg-[#0d1834] px-4 py-2.5 text-sm font-semibold text-white">Executive report</Link><Link to="/" className="rounded-full border border-blue-100 px-4 py-2.5 text-sm font-semibold text-slate-600">Analyze another</Link></div><ScreenChat context={screenContext(workflow)} /></section>;
}

function StepDetail({ step, score, onGenerate }: { step: Workflow["steps"][number]; score?: StepScore; onGenerate: () => void }) { return <article className="rounded-[28px] border border-blue-100 bg-white p-6 shadow-card sm:p-8"><div className="flex flex-col justify-between gap-5 border-b border-slate-100 pb-6 sm:flex-row sm:items-start"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand">Current-state step</p><h2 className="mt-2 font-display text-3xl font-semibold tracking-tight text-ink">{step.name}</h2></div>{score && <div className="flex items-center gap-3"><VerdictBadge verdict={score.verdict} />{score.verdict !== "leave_as_is" && <button type="button" onClick={onGenerate} className="rounded-full bg-brand px-4 py-2 text-xs font-bold text-white transition hover:bg-brand-deep">{score.verdict === "automate" ? "Open blueprint" : "Open redesign"}</button>}</div>}</div><div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_270px]"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">What happens</p><BulletList text={step.description} /><details className="group mt-7 rounded-2xl bg-cloud p-4" open><summary className="cursor-pointer list-none text-xs font-bold uppercase tracking-[0.16em] text-slate-500">Decision reasoning <span className="float-right text-brand group-open:rotate-90">›</span></summary><p className="mt-3 text-sm leading-6 text-slate-600">{score?.reasoning ?? "Waiting for score..."}</p></details></div>{score && <ScorePanel score={score} />}</div></article>; }
function ScorePanel({ score }: { score: StepScore }) { return <div className="space-y-3"><div className="rounded-[22px] bg-brand-gradient p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-blue-100">AI suitability</p><p className="mt-2 font-display text-6xl font-semibold">{score.scores.ai_suitability}<span className="ml-1 text-xl text-blue-100">/5</span></p><p className="mt-2 text-xs text-blue-100">Incremental value beyond rules</p></div><div className="grid grid-cols-2 gap-2">{Object.entries(score.scores).filter(([key]) => key !== "ai_suitability").map(([key, value]) => <ScoreTooltip key={key} dimension={key} explanation={score.reasoning}><div className="rounded-2xl border border-blue-100 bg-white p-3"><p className="text-[10px] uppercase leading-4 tracking-wide text-slate-400">{key.replaceAll("_", " ")}</p><p className="mt-1 font-display text-2xl font-semibold text-ink">{value}<span className="ml-1 text-xs font-normal text-slate-400">/5</span></p></div></ScoreTooltip>)}</div><div className="rounded-2xl border border-blue-100 bg-blue-50/60 p-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-brand">Risk if unaddressed</p><p className="mt-1 font-display text-xl font-semibold text-ink">{riskScore(score)}<span className="ml-1 text-xs font-normal text-slate-500">/5 · {riskLabel(riskScore(score))}</span></p><p className="mt-2 text-xs leading-5 text-slate-600">{riskExplanation(score)}</p></div></div>; }
function BulletList({ text }: { text: string }) { return <ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600">{textBullets(text).map((item, index) => <li key={`${item}-${index}`} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brand" />{item}</li>)}</ul>; }
function Eyebrow({ children, light = false }: { children: ReactNode; light?: boolean }) { return <span className={`inline-flex rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-[0.16em] ${light ? "bg-white/15 text-blue-100" : "bg-blue-50 text-brand"}`}>{children}</span>; }
function EmptyReview() { return <section className="mx-auto max-w-2xl rounded-[28px] border border-blue-100 bg-white p-10 text-center shadow-card"><Eyebrow>No workflow loaded</Eyebrow><h1 className="mt-4 font-display text-3xl font-semibold">Start with an upload</h1><Link to="/" className="mt-7 inline-flex rounded-full bg-brand px-5 py-3 text-sm font-bold text-white">Go to upload</Link></section>; }
