import { useEffect, useState, type ReactNode } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { getWorkflow } from "../api/workflows";
import { VerdictBadge } from "../components/VerdictBadge";
import { WorkflowDiagram } from "../components/WorkflowDiagram";
import { ScreenChat } from "../components/ScreenChat";
import { ScoreTooltip } from "../components/ScoreTooltip";
import type { StepScore, Workflow } from "../types/workflow";
import { riskExplanation, riskLabel, riskScore, screenContext, textBullets } from "../utils/workflow";

export function StepReviewPage() {
  const { workflowId } = useParams(); const navigate = useNavigate();
  const [workflow, setWorkflow] = useState<Workflow | null>(null); const [selectedId, setSelectedId] = useState<string>(); const [view, setView] = useState<"steps" | "map">("steps"); const [error, setError] = useState("");
  useEffect(() => { if (!workflowId) return; getWorkflow(workflowId).then((loaded) => { setWorkflow(loaded); setSelectedId((current) => current ?? loaded.steps[0]?.step_id); sessionStorage.setItem("currentWorkflow", JSON.stringify(loaded)); }).catch((requestError) => { const cached = sessionStorage.getItem("currentWorkflow"); if (cached) { try { const loaded = JSON.parse(cached) as Workflow; if (loaded.workflow_id === workflowId) { setWorkflow(loaded); setSelectedId((current) => current ?? loaded.steps[0]?.step_id); return; } } catch { /* Ignore malformed browser state and show the request error. */ } } setError(requestError instanceof Error ? requestError.message : "Workflow load failed."); }); }, [workflowId]);
  if (error) return <section className="rounded-[24px] bg-red-50 p-8 text-red-700">{error}</section>;
  if (!workflow || workflow.workflow_id !== workflowId) return <EmptyReview />;
  const selected = workflow.steps.find((step) => step.step_id === selectedId) ?? workflow.steps[0]; const score = workflow.scores.find((item) => item.step_id === selected.step_id);
  const updateWorkflow = (updated: Workflow) => { setWorkflow(updated); sessionStorage.setItem("currentWorkflow", JSON.stringify(updated)); };
  return <section className="mx-auto max-w-7xl"><Hero workflow={workflow} score={score} /><DomainWarning visible={workflow.domain_relevance_warning} /><ConsistencyBanner flags={workflow.consistency_flags} /><div className="mt-6 flex flex-wrap items-center justify-between gap-3"><div className="inline-flex rounded-full border border-blue-100 bg-white p-1 shadow-card" role="tablist" aria-label="Step review view"><Tab active={view === "steps"} onClick={() => setView("steps")}>Workflow Steps</Tab><Tab active={view === "map"} onClick={() => setView("map")}>Sequence Map</Tab></div><div className="flex flex-wrap gap-2"><Link to={`/redesigned-flow/${workflow.workflow_id}`} className="rounded-full bg-brand px-4 py-2.5 text-xs font-bold text-white">Browse generated flow ↗</Link><Link to={`/report/${workflow.workflow_id}`} className="rounded-full bg-[#0d1834] px-4 py-2.5 text-xs font-bold text-white">Executive report</Link><Link to="/" className="rounded-full border border-blue-100 px-4 py-2.5 text-xs font-semibold text-slate-600">Analyze another</Link></div></div>{view === "steps" ? <div className="mt-6 grid gap-6 lg:grid-cols-[280px_minmax(0,1fr)]"><StepList workflow={workflow} selectedId={selected.step_id} onSelect={setSelectedId} /><StepDetail step={selected} score={score} onGenerate={() => score?.verdict === "automate" ? navigate(`/automation/${workflow.workflow_id}/${selected.step_id}`) : navigate(`/redesign/${workflow.workflow_id}/${selected.step_id}`)} /></div> : <div className="mt-6"><div className="mb-4 flex items-end justify-between gap-4"><div><Eyebrow>Sequence map</Eyebrow><h2 className="mt-2 font-display text-2xl font-semibold">How the work moves</h2></div><span className="text-xs text-slate-500">Click a node to inspect</span></div><WorkflowDiagram workflow={workflow} selectedStepId={selected.step_id} onStepSelect={setSelectedId} onWorkflowChange={updateWorkflow} /></div>}<ScreenChat context={screenContext(workflow)} /></section>;
}

function DomainWarning({ visible }: { visible: boolean }) {
  const [dismissed, setDismissed] = useState(false);
  if (!visible || dismissed) return null;
  return <aside className="mt-5 flex items-start justify-between gap-3 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-950 shadow-card" aria-label="Domain relevance warning"><p><span className="font-semibold">This document doesn&apos;t appear to describe an investment management workflow</span> — results may not be meaningful.</p><button type="button" onClick={() => setDismissed(true)} className="shrink-0 rounded-full px-2 py-1 text-xs font-semibold text-amber-800 hover:bg-amber-100" aria-label="Dismiss domain relevance warning">Dismiss</button></aside>;
}

function ConsistencyBanner({ flags }: { flags: Workflow["consistency_flags"] }) {
  const [dismissed, setDismissed] = useState(false);
  const [expanded, setExpanded] = useState(false);
  if (dismissed || flags.length === 0) return null;
  return <aside className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-amber-950 shadow-card" aria-label="Consistency check results"><div className="flex flex-wrap items-center justify-between gap-3"><button type="button" onClick={() => setExpanded((current) => !current)} className="text-left text-sm font-semibold">{flags.length} potential gap{flags.length === 1 ? "" : "s"} found <span className="font-normal text-amber-800">· click to review</span></button><button type="button" onClick={() => setDismissed(true)} className="rounded-full px-2 py-1 text-xs font-semibold text-amber-800 hover:bg-amber-100" aria-label="Dismiss consistency check">Dismiss</button></div>{expanded && <ul className="mt-3 space-y-3 border-t border-amber-200 pt-3 text-sm">{flags.map((flag, index) => <li key={`${flag.referenced_action}-${index}`}><p className="font-semibold">{flag.referenced_action}</p><blockquote className="mt-1 border-l-2 border-amber-300 pl-3 text-amber-800">“{flag.evidence_quote}”</blockquote></li>)}</ul>}</aside>;
}

function Hero({ workflow, score }: { workflow: Workflow; score?: StepScore }) { return <div className="relative overflow-hidden rounded-[28px] bg-brand-radial px-7 py-8 text-white shadow-float sm:px-10"><div className="relative z-10 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><Eyebrow light>Step review · {workflow.steps.length} steps</Eyebrow><h1 className="mt-5 max-w-3xl font-display text-4xl font-semibold tracking-tight sm:text-5xl">{workflow.name.replaceAll("_", " ")}</h1><p className="mt-3 text-sm text-blue-100">One decision at a time, with the evidence behind it always in reach.</p></div>{score && <div className="rounded-[22px] border border-white/20 bg-white/10 p-4 backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-blue-100">Selected verdict</p><div className="mt-2"><VerdictBadge verdict={score.verdict} /></div></div>}</div><div className="pointer-events-none absolute -right-10 -top-20 h-64 w-64 rounded-full bg-brand-soft/30 blur-3xl" /></div>; }
function StepList({ workflow, selectedId, onSelect }: { workflow: Workflow; selectedId: string; onSelect: (id: string) => void }) { return <aside className="space-y-3"><div className="flex items-center justify-between"><div><Eyebrow>Workflow steps</Eyebrow><p className="mt-2 text-xs text-slate-500">Select a step to inspect</p></div><span className="font-display text-sm font-semibold text-brand">{String(Number(selectedId)).padStart(2, "0")} / {workflow.steps.length}</span></div>{workflow.steps.map((step) => { const item = workflow.scores.find((entry) => entry.step_id === step.step_id); const active = step.step_id === selectedId; return <button key={step.step_id} type="button" onClick={() => onSelect(step.step_id)} className={`w-full cursor-pointer rounded-[20px] border p-4 text-left transition ${active ? "border-brand bg-white shadow-card ring-2 ring-blue-100" : "border-blue-100 bg-white/70 hover:border-blue-300 hover:bg-white"}`}><div className="flex items-center justify-between gap-3"><span className={`grid h-8 w-8 place-items-center rounded-full text-xs font-bold ${active ? "bg-brand text-white" : "bg-blue-50 text-brand"}`}>{String(Number(step.step_id)).padStart(2, "0")}</span>{item && <VerdictBadge verdict={item.verdict} />}</div><p className="mt-3 line-clamp-2 text-sm font-semibold text-ink">{step.name}</p></button>; })}</aside>; }
function StepDetail({ step, score, onGenerate }: { step: Workflow["steps"][number]; score?: StepScore; onGenerate: () => void }) { return <article className="rounded-[28px] border border-blue-100 bg-white p-6 shadow-card sm:p-8"><div className="flex flex-col justify-between gap-5 border-b border-slate-100 pb-6 sm:flex-row sm:items-start"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand">Current-state step</p><h2 className="mt-2 font-display text-3xl font-semibold tracking-tight text-ink">{step.name}</h2></div>{score && <div className="flex items-center gap-3"><VerdictBadge verdict={score.verdict} />{score.verdict !== "leave_as_is" && <button type="button" onClick={onGenerate} className="rounded-full bg-brand px-4 py-2 text-xs font-bold text-white transition hover:bg-brand-deep">{score.verdict === "automate" ? "Open blueprint" : "Open redesign"}</button>}</div>}</div><section className="mt-6 rounded-[22px] border border-blue-100 bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">What happens</p><BulletList text={step.description} /></section>{score && <><section className="mt-4 rounded-[22px] border border-blue-100 bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Decision reasoning</p><BulletList text={score.reasoning} /></section><div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1fr)_300px]"><RiskCard score={score} /><MetricGrid score={score} /></div></>}</article>; }
function RiskCard({ score }: { score: StepScore }) { const risk = riskScore(score); return <div className="mt-6 rounded-2xl border border-blue-100 bg-blue-50/60 p-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-brand">Risk if unaddressed</p><p className="mt-1 font-display text-xl font-semibold text-ink">{risk}/5<span className="ml-1 text-xs font-normal text-slate-500">· {riskLabel(risk)}</span></p><p className="mt-2 text-xs leading-5 text-slate-600">{riskExplanation(score)}</p></div>; }
function MetricGrid({ score }: { score: StepScore }) { return <div className="grid grid-cols-2 gap-3">{Object.entries(score.scores).map(([key, value]) => <ScoreTooltip key={key} dimension={key} explanation={score.reasoning}><div className="min-h-[92px] rounded-2xl border border-blue-100 bg-white p-3"><p className="text-[10px] uppercase leading-4 tracking-wide text-slate-400">{key.replaceAll("_", " ")}</p><p className="mt-2 font-display text-2xl font-semibold text-ink">{value}<span className="ml-1 text-xs font-normal text-slate-400">/5</span></p></div></ScoreTooltip>)}</div>; }
function BulletList({ text }: { text: string }) { return <ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600">{textBullets(text).slice(0, 4).map((item, index) => <li key={`${item}-${index}`} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brand" />{item}</li>)}</ul>; }
function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: ReactNode }) { return <button type="button" role="tab" aria-selected={active} onClick={onClick} className={`rounded-full px-5 py-2.5 text-sm font-semibold transition ${active ? "bg-brand text-white shadow" : "text-slate-500 hover:text-brand"}`}>{children}</button>; }
function Eyebrow({ children, light = false }: { children: ReactNode; light?: boolean }) { return <span className={`inline-flex rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-[0.16em] ${light ? "bg-white/15 text-blue-100" : "bg-blue-50 text-brand"}`}>{children}</span>; }
function EmptyReview() { return <section className="mx-auto max-w-2xl rounded-[28px] border border-blue-100 bg-white p-10 text-center shadow-card"><Eyebrow>No workflow loaded</Eyebrow><h1 className="mt-4 font-display text-3xl font-semibold">Start with an upload</h1><Link to="/" className="mt-7 inline-flex rounded-full bg-brand px-5 py-3 text-sm font-bold text-white">Go to upload</Link></section>; }
