import { BrowserRouter, Route, Routes } from "react-router-dom";
import { AppShell } from "./components/AppShell";
import { PlaceholderPage } from "./pages/PlaceholderPage";
import { StepReviewPage } from "./pages/StepReviewPage";
import { UploadPage } from "./pages/UploadPage";

export function App() {
  return <BrowserRouter><Routes><Route element={<AppShell />}><Route path="/" element={<UploadPage />} /><Route path="/review/:workflowId" element={<StepReviewPage />} /><Route path="/automation/:workflowId" element={<PlaceholderPage eyebrow="03 / Automation blueprint" title="A practical automation map, not another AI experiment." description="This view will show the templated mechanism, trigger, rationale, and static diagram for steps judged suitable for conventional automation." dependency="Automation Blueprint Generator and its API route" />} /><Route path="/redesign/:workflowId" element={<PlaceholderPage eyebrow="03 / Redesign proposal" title="Fix the workflow before you accelerate it." description="This view will present the agent-first redesign proposal and its read-only visual workflow representation." dependency="Redesign Generator and its API route" />} /><Route path="/dashboard" element={<PlaceholderPage eyebrow="04 / Portfolio view" title="See the exception pattern across the book of work." description="This portfolio view will map complexity and exception concentration across analyzed workflows." dependency="Analyzed workflow aggregation endpoint" />} /><Route path="/resume" element={<PlaceholderPage eyebrow="04 / Resume session" title="Pick up exactly where the work paused." description="This control will list the latest incomplete workflow and return the user to its last completed stage." dependency="WorkflowSession persistence and resume endpoint" />} /></Route></Routes></BrowserRouter>;
}
